version: "3.9"

services:
  db:
    image: postgres:15
    container_name: blackenshovel-db
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: blackenshovel
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: blackenshovel-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: blackenshovel    
    ports:
      - "8080:8080"
    command: ["./blackenshovel-service"]

volumes:
  db_data:
